-- Export this query result as CSV from the Supabase SQL editor.
-- Save it locally as data/checkins.csv, then run:
-- python ml/train_symptom_model.py data/checkins.csv --all-targets

select
  c.id as checkin_id,
  c.user_id,
  c.snapshot_id,
  c.zip_code as checkin_zip_code,
  c.felt_impact,
  c.respiratory_symptoms,
  c.allergy_symptoms,
  c.heat_symptoms,
  c.headache_or_fatigue,
  c.avoided_outdoor_activity,
  c.used_rescue_medication,
  c.missed_work_school_activity,
  c.symptom_severity,
  c.created_at as checkin_created_at,
  s.zip_code,
  s.city,
  s.state,
  s.latitude,
  s.longitude,
  s.model_version,
  s.model_score,
  s.health_risk,
  s.respiratory_risk,
  s.air_quality,
  s.aqi,
  s.dominant_pollutant,
  s.pollutant_risk,
  s.heat_risk,
  s.uv_risk,
  s.alert_risk,
  s.flu_activity,
  s.covid_activity,
  s.covid_coverage,
  s.forecast_average_score,
  s.forecast_peak_score,
  s.forecast_best_window,
  s.forecast_worst_window,
  s.forecast_allergy_peak_score,
  s.forecast_allergy_peak_window,
  s.forecast_pollen_risk,
  s.equity_score,
  s.equity_level,
  s.places_chronic_burden_score,
  s.places_asthma,
  s.places_copd,
  s.places_smoking,
  s.places_obesity,
  s.places_diabetes,
  s.created_at as snapshot_created_at
from public.symptom_checkins c
left join public.health_snapshots s on s.id = c.snapshot_id
order by c.created_at desc;
